### ISSUE TITLE
you can easy make russian lang support

### ISSUE THREAD

**Issue by v-sh** [munshkr/freeling-analyzer-ruby#14]
sorry for my english

freeling support russian
but this bindings not
when i try use it like:

analyzer = FreeLing::Analyzer.new(text, language: :ru)

i have an error in the latest_error_log:
"NEC: Error opening file /usr/share/freeling/ru/nec/nec-ab.dat\n"

i just make a duty fix in analizer.rb:
comment "--nec"

it works for me now, but i don't know why

maybe i'll make pull request later

**Comment by munshkr** [comment]
Hi! The `--nec` parameter is there to enable the NEC (named-entity classification) module. I'm not sure but maybe Freeling hasn't a proper NEC module for Russian. I can't check this at the moment, but I will see later today if that's the cause of it.

**Comment by merqlove** [comment]
Freeling doesn't support NER in Russian language out from the box.
